num_channels: 1024
cpu_offload: False
keep_batch_sharded: True
use_obs_fuser: False

model:
  _target_: anemoi.models.models.ens_obsfuser.AnemoiEnsObsFuser

layer_kernels:
  # The layer_kernels can be adjusted per model component, but are defined here for convenience.
  LayerNorm:
    _target_: torch.nn.LayerNorm
  Linear:
    _target_: torch.nn.Linear
  Activation:
    _target_: torch.nn.GELU
  QueryNorm:
    _target_: anemoi.models.layers.normalization.AutocastLayerNorm
    bias: False
  KeyNorm:
    _target_: anemoi.models.layers.normalization.AutocastLayerNorm
    bias: False

# Noise Injection
noise_injector:
  _target_: anemoi.models.layers.ensemble.NoiseConditioning
  noise_std: 1.0
  noise_channels_dim: 4
  noise_mlp_hidden_dim: 32
  inject_noise: True

# Kernels for Processor (Conditional LayerNorm)
processor_layer_kernels:
  LayerNorm:
    _target_: anemoi.models.layers.normalization.ConditionalLayerNorm
    normalized_shape: ${model.num_channels} # Assumes resolved at runtime
    condition_shape: ${model.noise_injector.noise_channels_dim}
    w_one_bias_zero_init: True
    autocast: false
  Linear:
    _target_: torch.nn.Linear
  Activation:
    _target_: torch.nn.GELU
  QueryNorm:
    _target_: anemoi.models.layers.normalization.AutocastLayerNorm
    bias: False
  KeyNorm:
    _target_: anemoi.models.layers.normalization.AutocastLayerNorm
    bias: False

processor:
  _target_: anemoi.models.layers.processor.GraphTransformerProcessor
  trainable_size: ${model.trainable_parameters.hidden2hidden}
  sub_graph_edge_attributes: ${model.attributes.edges}
  num_layers: 16
  num_chunks: 2 # do not change
  mlp_hidden_ratio: 4
  num_heads: 16
  qk_norm: True
  cpu_offload: ${model.cpu_offload}
  layer_kernels: ${model.processor_layer_kernels}

encoder:
  _target_: anemoi.models.layers.mapper.GraphTransformerForwardMapper
  trainable_size: ${model.trainable_parameters.data2hidden}
  sub_graph_edge_attributes: ${model.attributes.edges}
  num_chunks: 4
  mlp_hidden_ratio: 4
  num_heads: 16
  qk_norm: False
  cpu_offload: ${model.cpu_offload}
  layer_kernels: ${model.layer_kernels}

decoder:
  _target_: anemoi.models.layers.mapper.GraphTransformerBackwardMapper
  trainable_size: ${model.trainable_parameters.hidden2data}
  sub_graph_edge_attributes: ${model.attributes.edges}
  num_chunks: 4
  mlp_hidden_ratio: 4
  num_heads: 16
  initialise_data_extractor_zero: False
  qk_norm: False
  cpu_offload: ${model.cpu_offload}
  layer_kernels: ${model.layer_kernels}

decoder_extra:
  _target_: anemoi.models.layers.mapper.GraphTransformerBackwardMapper
  trainable_size: ${model.trainable_parameters.hidden2data}
  sub_graph_edge_attributes: ${model.attributes.edges}
  num_chunks: 4
  mlp_hidden_ratio: 4
  num_heads: 16
  initialise_data_extractor_zero: False
  qk_norm: False
  cpu_offload: ${model.cpu_offload}
  layer_kernels: ${model.layer_kernels}

trainable_parameters:
  data: 0
  hidden: 0
  data2hidden: 0
  hidden2data: 0
  hidden2hidden: 0

output_mask:
  _target_: anemoi.training.utils.masks.NoOutputMask

attributes:
  edges:
  - edge_length
  - edge_dirs
  nodes: []

bounding:
  - - _target_: anemoi.models.layers.bounding.ReluBounding
      variables:
      - tp
